# Generated by Django 4.2.10 on 2024-02-26 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.PositiveIntegerField()),
                ('total_cost', models.PositiveBigIntegerField()),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('transaction_type', models.CharField(default='IN')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit card'), ('Master Card', 'Master Card'), ('Bank Cheque', 'Bank cheque'), ('Bkash', 'Bkash'), ('Sure Cash', 'Sure Cash'), ('DBBL Mobile', 'DBBL Mobile'), ('DBBL Card', 'DBBL Card'), ('Nagad', 'Nagad'), ('UCash', 'UCash'), ('Payoneer', 'Payoneer')], max_length=50)),
                ('paid_ammount', models.PositiveBigIntegerField()),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['purchase_date'],
            },
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=5)),
                ('payment_method', models.CharField(max_length=50)),
                ('amount', models.PositiveBigIntegerField()),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
