# Generated by Django 4.2.10 on 2024-02-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicecategories',
            options={'ordering': ['-id']},
        ),
    ]
