# Generated by Django 4.2.10 on 2024-02-13 17:34

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImg',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
