# Generated by Django 4.2.10 on 2024-02-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_productimg_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='year_field',
            field=models.DateField(blank=True, null=True),
        ),
    ]
