# Generated by Django 4.2.10 on 2024-02-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_purchase_alter_inventory_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='total_cost',
        ),
    ]
