# Generated by Django 4.2.10 on 2024-02-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_devicecategories_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicecategories',
            options={'ordering': ['id']},
        ),
    ]
