# Generated by Django 4.2.10 on 2024-03-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_name_generaluser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlineup',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
