# Generated by Django 4.2.10 on 2024-02-13 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_year_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplierId',
        ),
        migrations.AddField(
            model_name='inventory',
            name='supplierId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
        ),
    ]
