# Generated by Django 4.2.10 on 2024-02-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_purchase_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='transaction_type',
            field=models.CharField(blank=True, default='IN', null=True),
        ),
    ]
