# Generated by Django 4.2.10 on 2024-02-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_supplierid_inventory_supplierid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='year_field',
            new_name='released_year',
        ),
    ]
