# Generated by Django 4.2.10 on 2024-03-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_productlineup_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluser',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
