# Generated by Django 4.2.10 on 2024-02-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_device_quantity_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
