# Generated by Django 4.2.10 on 2024-02-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_year_field_product_released_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='productId',
            new_name='product',
        ),
    ]
