# Generated by Django 4.2.10 on 2024-02-27 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_purchase_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
