# Generated by Django 4.2.10 on 2024-02-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_supplier_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
