# Generated by Django 4.2.10 on 2024-03-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_productlineup_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlineup',
            name='token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
