# Generated by Django 4.2.10 on 2024-03-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_productlineup_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlineup',
            name='subtotal',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
