# Generated by Django 4.2.10 on 2024-02-28 12:34

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_productimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImg',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.product_image_path),
        ),
    ]
