# Generated by Django 4.2.10 on 2024-03-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_productlineup_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlineup',
            name='sale_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
