# Generated by Django 4.2.10 on 2024-03-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_purchase_brand_alter_purchase_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['-id']},
        ),
    ]
