# Generated by Django 4.2.10 on 2024-03-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_sales_invoice_list_sales_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
