# Generated by Django 4.2.10 on 2024-03-14 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_brand_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='product',
        ),
    ]
