# Generated by Django 4.2.10 on 2024-03-14 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_supplier_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='address',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='email',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
        ),
    ]
