# Generated by Django 4.2.10 on 2024-03-22 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_transaction_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlineup',
            name='sale_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sales'),
        ),
    ]
