# Generated by Django 4.2.10 on 2024-03-28 18:14

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_productlineup_sale_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.profile_image_path),
        ),
    ]
