# Generated by Django 4.2.10 on 2024-03-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_purchase_address_remove_purchase_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='due_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
